### PR TITLE
fix- bug in empty task title

### LINKED ISSUE #17: Disable add/save button when there is no task title
when task.title is empty string disable the button

### PR DESCRIPTION
**Pull request by AvaniSujith**
disabled add task button and save button whenever title given is empty 
closes #17

### CODE REVIEW

File: src/components/AddTask.vue [hunk 1]
```diff
@@ -15,12 +15,15 @@ const notificationStore = useNotificationStore();
 
 const taskTitle = ref<string>("");
 
+const isAddButtonDisabled = computed(() => {
+  return taskTitle.value.length;
+});
+
```
Comment (Musthaq-Ahmad) [inline src/components/AddTask.vue:21]:
```suggestion
const isAddButtonDisabled = computed(() => {
  return !taskTitle.value.trim().length;
});

```

File: src/components/TaskList.vue [hunk 2]
```diff
@@ -30,6 +30,10 @@ const handleDelete = (id: number) => {
 
 const isEditing = (id: number) => editingTaskId.value === id;
 
+const isEmptyTitle = computed(() => {
+  return editingTaskTitle.value.length;
+});
+
```
Comment (Musthaq-Ahmad) [inline src/components/TaskList.vue:36]: same here

File: src/components/TaskList.vue [hunk 3]
```diff
@@ -51,6 +55,12 @@ const buttonContent = (id: number) => {
   return isEditing(id) ? "save" : "edit";
 };
 
+const isSaveButtonDisabled = (task: Task) => {
+  return !isEmptyTitle.value && buttonContent(task.id) === "save"
+    ? true
+    : false;
+};
```
Comment (Musthaq-Ahmad) [inline src/components/TaskList.vue:62]:
```suggestion
const isSaveButtonDisabled = (id: number) => {
  return isEmptyTitle.value && isEditing(id);
};

```

**Review by Musthaq-Ahmad — CHANGES_REQUESTED** [review]
